import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../app/providers.dart';
import '../../core/constants/prayer_types.dart';
import '../calendar/calendar_controller.dart';
import '../calendar/calendar_picker.dart';

class AddQazaScreen extends ConsumerStatefulWidget { const AddQazaScreen({super.key}); @override ConsumerState<AddQazaScreen> createState()=>_AddQazaScreenState(); }
class _AddQazaScreenState extends ConsumerState<AddQazaScreen>{
 int step=0; Set<PrayerType> prayers={}; int existing=0,newCount=0; bool checking=false,saving=false,calendarLoading=false; Map<DateTime,Set<PrayerType>> calendarAvailability={}; int request=0;
 DateSelectionMode get mode=>ref.watch(calendarControllerProvider).selectionMode; List<DateTime> get dates=>ref.read(calendarControllerProvider).datesForStorage.toList();
 Future<void> loadMonth(DateTime month) async { final token=++request; setState(()=>calendarLoading=true); try { final first=DateTime(month.year,month.month,1); final last0=DateTime(month.year,month.month+1,0); final today=ref.read(calendarTodayProvider); final last=last0.isAfter(today)?today:last0; if(last.isBefore(first)){if(mounted&&token==request)setState(()=>calendarAvailability={});return;} final map=await ref.read(qazaServiceProvider).getAvailablePrayersByDate(userId:ref.read(requiredUserIdProvider),dates:[for(var d=first;!d.isAfter(last);d=d.add(const Duration(days:1)))d]); if(mounted&&token==request)setState(()=>calendarAvailability=map); } finally { if(mounted&&token==request)setState(()=>calendarLoading=false); } }
 Future<void> refresh() async { if(checking||dates.isEmpty||prayers.isEmpty)return; setState(()=>checking=true); try { final a=await ref.read(qazaServiceProvider).analyzeAvailability(userId:ref.read(requiredUserIdProvider),dates:dates,prayerTypes:prayers); if(mounted)setState((){existing=a.unavailableCount;newCount=a.newCount;}); } finally {if(mounted)setState(()=>checking=false);} }
 void nextDates(){if(dates.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Choose at least one date.')));return;}setState(()=>step=2);}
 Future<void> toggle(PrayerType p,bool v)async{setState(()=>v?prayers.add(p):prayers.remove(p));if(prayers.isEmpty){setState((){existing=0;newCount=0;});return;}await refresh();}
 Future<void> save()async{if(saving||prayers.isEmpty||newCount<=0)return;setState(()=>saving=true);try{final n=newCount;await ref.read(qazaServiceProvider).recordQazaForDates(userId:ref.read(requiredUserIdProvider),dates:dates,prayerTypes:prayers);if(!mounted)return;await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Qaza records created'),content:Text('$n record${n==1?'':'s'} were added to your ledger.'),actions:[FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Done'))]));if(mounted)Navigator.pop(context,n);}finally{if(mounted)setState(()=>saving=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Add Qaza'),leading:IconButton(onPressed:()=>step==0?Navigator.pop(context):setState(()=>step--),icon:Icon(step==0?Icons.close:Icons.arrow_back))),body:SafeArea(child:Column(children:[_Header(step),Expanded(child:switch(step){0=>modeStep(),1=>dateStep(),_=>prayerStep()})])));
 Widget modeStep()=>ListView(padding:const EdgeInsets.all(20),children:[Text('Step 1 of 3 • Range Setup',style:Theme.of(context).textTheme.labelLarge),const SizedBox(height:8),Text('Add Qaza',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:20),SegmentedButton<DateSelectionMode>(segments:const[ButtonSegment(value:DateSelectionMode.single,label:Text('Single')),ButtonSegment(value:DateSelectionMode.range,label:Text('Range')),ButtonSegment(value:DateSelectionMode.multiple,label:Text('Multiple'))],selected:{mode},onSelectionChanged:(v)=>ref.read(calendarControllerProvider.notifier).setSelectionMode(v.first)),const SizedBox(height:20),const _Info(text:'Gregorian is the source of truth. Each date + prayer combination is an independent Qaza record.'),const SizedBox(height:24),FilledButton(onPressed:()=>setState(()=>step=1),child:const Text('Continue'))]);
 Widget dateStep(){final s=ref.watch(calendarControllerProvider);return ListView(padding:const EdgeInsets.all(20),children:[Text('Step 2 of 3 • Date Selection',style:Theme.of(context).textTheme.labelLarge),const SizedBox(height:8),Text(s.selectionMode==DateSelectionMode.single?'Choose a date':s.selectionMode==DateSelectionMode.range?'Choose a date range':'Choose multiple dates',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:8),Text('A date is disabled only when no prayer remains eligible.',style:Theme.of(context).textTheme.bodyMedium),const SizedBox(height:16),CalendarPicker(availablePrayersByDate:calendarAvailability,availabilityLoading:calendarLoading,onMonthChanged:loadMonth),const SizedBox(height:16),FilledButton(onPressed:dates.isEmpty?null:nextDates,child:const Text('Next: Choose missed prayers'))]);}
 Widget prayerStep(){final all=prayers.length==PrayerType.values.length;return ListView(padding:const EdgeInsets.fromLTRB(20,12,20,28),children:[Text('Step 3 of 3 • Ledger Entry',style:Theme.of(context).textTheme.labelLarge),const SizedBox(height:8),Text('Missed Prayers',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:8),Text('${dates.length} ${dates.length==1?'day':'days'} • Select every prayer that was missed.'),const SizedBox(height:16),Row(children:[Expanded(child:OutlinedButton(onPressed:checking||all?null:(){prayers.addAll(PrayerType.values);refresh();},child:Text(all?'All selected':'Select All'))),const SizedBox(width:10),Expanded(child:OutlinedButton(onPressed:checking||prayers.isEmpty?null:(){setState(()=>prayers.clear());setState((){existing=0;newCount=0;});},child:const Text('Clear')))]),const SizedBox(height:12),for(final p in PrayerType.values)Card(child:CheckboxListTile(value:prayers.contains(p),onChanged:saving||checking?null:(v)=>toggle(p,v==true),secondary:CircleAvatar(child:Icon(p.icon)),title:Text(p.label),subtitle:Text(p.rakats))),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[_Row('Dates','${dates.length}'),_Row('Prayers per date','${prayers.length}'),_Row('Existing combinations','$existing'),_Row('New records','$newCount',bold:true)]))),const SizedBox(height:16),FilledButton(onPressed:saving||checking||newCount<=0?null:save,child:Text(saving?'Creating Records...':'Review & Create Records'))]);}
}
class _Header extends StatelessWidget{const _Header(this.step);final int step;@override Widget build(BuildContext c){final s=Theme.of(c).colorScheme;return Padding(padding:const EdgeInsets.all(16),child:Row(children:[for(var i=0;i<3;i++)... [CircleAvatar(radius:14,backgroundColor:i<=step?s.primary:s.surfaceContainerHighest,child:Text('${i+1}',style:TextStyle(color:i<=step?s.onPrimary:null))),if(i<2)Expanded(child:Container(height:2,color:i<step?s.primary:s.outlineVariant))]]));}}
class _Info extends StatelessWidget{const _Info({required this.text});final String text;@override Widget build(BuildContext c){final s=Theme.of(c).colorScheme;return Container;padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:s.primaryContainer,borderRadius:BorderRadius.circular(14)),child:Text(text,style:TextStyle(color:s.onPrimaryContainer));}}
class _Row extends StatelessWidget{const _Row(this.a,this.b,{this.bold=false});final String a,b;final bool bold;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(children:[Expanded(child:Text(a)),Text(b,style:bold?Theme.of(c).textTheme.titleMedium:null)]));}
